name: Test Webhook Auth
description: Simple webhook workflow to test authentication bypass
trigger: webhook
output: json
steps:
  - module: utilities.javascript.execute
    id: return-webhook-data
    inputs:
      code: |
        return {
          message: "Webhook received successfully!",
          timestamp: new Date().toISOString()
        };
